Reduce API pull requests to 1/sec for maximum_gitlab_api_requests_per_second
mvisonneau/gitlab-ci-pipelines-exporter pull request #257
Opened 2021-04-20 11:23 UTC by dnsmichi

## Details:

- https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/253
- https://gitlab.com/gitlab-org/gitlab/-/issues/327919#note_555854856

## Tests

![Screenshot 2021-04-20 at 13 20 12](https://user-images.githubusercontent.com/382049/115387882-8834bf00-a1db-11eb-8e18-f963484e0d99.png)

2021-04-20 11:43 UTC, dnsmichi commented
Modified the example settings after reviewing the docs on a global level: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md

2021-04-21 09:01 UTC, mvisonneau requested changes
thanks for the change @dnsmichi, I made a small comment about the examples definitions but otherwise I am happy to merge it.

2021-04-21 09:01 UTC, mvisonneau commented on examples/quickstart/gitlab-ci-pipelines-exporter.yml
> +pull:
and therefore same here 👍

2021-04-21 11:51 UTC, dnsmichi commented on examples/ha-setup/gitlab-ci-pipelines-exporter.yml
> +# Global pull settings
Good point. It is redundant, and users who upgrade will not recognize. Thanks for the kind review, I have adjusted it. :)

2021-04-21 11:51 UTC, dnsmichi commented on examples/quickstart/gitlab-ci-pipelines-exporter.yml
> +pull:
Addressed in a new commit, thanks 👍

2021-04-23 20:02 UTC, mvisonneau approved these changes
thanks @dnsmichi!

2021-04-23 20:02 UTC, merged